language: node_js
node_js: 4
before_install:
  - npm prune
  - rvm install 2.2.0
  - rvm use 2.2.0
before_cache: npm prune
install: npm install
script: ./scripts/test-ci.sh
branches:
  only:
    - master
    - develop
    - gh-pages
# force container based infra
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
sudo: false
cache:
  directories:
    - node_modules
env:
  global:
    - secure: Z8Ujy1KGYhmc+G5MAlPL377PVseJlhMjgr6jzTh6+IOnEEzXbYF2cvjvJfX7nJI16Y+/b5w+TV1relIocFZqA+wDsGIUNzyZxZH4/dqlVS5PQ190tRe6U27vMs/rIKSkhIl2hWdIJv38ScwFjAwAdSFePJ/ytgyHt5fNK0/Atd0CLrARK1PC8e6HhVQF5y8uZ10eH0TbByZGI3Ts+0VUkyxKcNpTZ+Y4QHEXSeDZ748j3acOfRDERyJI+LQ3y4zFf92dy1HQftaVbhkUU6yP+h2zg0+74fj+ZuSAYRc6OBab2PnJzgOQSN0wl1+PvUURRnfcru1ISr+RCQ9jZK0F2cDItcgxgAhO7wx6xgzrMLxE8Om4pIZ92bOJw85ZuFdiLrnwc9NKwYWvK7Rnh6WR6FUD2MLSHW7wxeo8EAKZ5SgmE3jJXfPadnJU1nEpMWhNA/Fhyr/xWwP2fiFHiycs+YXr4uDqjy90yxp/2Vb1BIr+WAEeYxhwXtS7EZm2n8tKFAl9xUc6eTU/ptYzwJ07RpxmByrBmNAqBDEWKdn1YKIZ4KolWri5PjFHF+Om9jdBLz6JWFkIS0gPQ95Bzr62oDErLgwdQgCi0PhREtEfj9fViOgiw9cyEG9Zh3z39jDWGy6GoLNB5FIbl7q+PZSi/I0rjA6kl7XAhF+lrhlNwzQ=
    - secure: OzAaYh3oG04VhBvuaCwq6GuIzRt6AuiyP1U8Q/arlC/3osFTRkyt64CMRlEZIso74C4eLGDeKGUhimBViurIzvDc2meu88ik41XFPZIJFXfeqrAhCELgJcnTCkRR4ztC3GA6DLVM02qhT/5ENRZ8pcqmHIKvvIoHWQ1l8s8dSBBUSD/0MxAyk9Opzg2qFxmZ8u5/HHSBwdYC0iy6sOBKbMoUocz2UHowfPk0efzZWAgKx3BQyKa+ImYUA0/o6Okmq04naqafjeVciWkXrF0YURPUVus0peNkqjxLdGMZeudxszPNp0fJ7rhSOKBlYwOtg9K98PMWWT1Ar7+TmssIYCrRTlVHeKmzNLOok/YBBvvcd+4kIo0IkO5dPFkpYQ//hKOF6mdvRa1KMlFwSgIVjMjrCikiHBnppheWXffWxWHGWPyfla0uTbwR6o4ONcRCJgTbPoi/xZOFS4ISBiECqCWjNhidOATSyPatBe2tABU2LN5WKqnPDzmnHl/ZusglpPiN1vrEsCyNsoyD6nFz0cVZasR4NKrgqQUzy8cxQhtNuupEW7nMCw8s79bcfE/CsP0A0sGOhDXti+ieAV1tra22US3LMUqysH2DwZakA3dbQtcFoO69Rp/7pWRnDwB2+mEPUJJrXq8tAspvjssalQYVHF6aDGgj5SFXAZYfArs=
    - secure: nbRmHD7x3bw92XaYgmWooZlqOuskiWYMCElryngLG4kxkjXd5c7sFUUu4BrEZHyWmTL+4HAD8lfHHsslEZjdLqgVElbNApKDHtuqNrF+K+WCRveo5ENi7cAuBoNZqpRJfA4kaTtHhRJi+jCrraKr2dCxFiNQzJ38rAAB+TyRDR3F9eC31lp879i4V3kfauu1Dx6CFFjZy/qYT6wTOqF/hH/PpN8TGwNlh8msAm44M4XZsvJ8p7RxOy8ku6k2O+TQ0EJR+ec8zSJLUa94A+C5DgemHQrn2PuQq2o67bizQjXQO6yZ9jSy/SFsNxHSQJXuMrusARDQmZH/t6hl0rxq+YSIFcFU9Hqi3htwYBkWvx/qahfRwo8MpQKQcukAD9mPzg+gTtpGOxepY2yqN0brLBZrJsUArLQzYWzGzILh4N0wUBsHYnfexFnOLLfWjgakfOwJdf7n7cQv8wRNrLnG1a3Muy8tkgF2pgCZ+jKt6/StnMLtO1FusNvR/7jYQwEfdqh8Oomk/U+xFBR+ZedRzcbyQfuFsEtpLxLN2RUW/tZAlNhILKt3LfdQ5O2w+RxVS+dU0qM5TTthnnUAVF4EYNJCypq32iliw7/KU1bjhAc/DYDkozEHUPIcMR6NFMJvlSOFtpe1p89EvaNfX6FE966mUedImFjiEEaauM/WNgw=
