language: node_js
node_js: 4
before_install: npm prune
before_cache: npm prune
install: npm install
script: ./scripts/test-ci.sh
deploy:
  # when master is pushed + test success: deploy website
  - provider: script
    skip_cleanup: true # avoid npm modules being removed
    script: npm run finish-release
    on:
      branch: master
  # when website is successfully deployed, update the documentation search index
  - provider: script
    skip_cleanup: true # avoid npm modules being removed
    script: npm run docs:update-website-search-index
    on:
      branch: gh-pages
branches:
  only:
    - master
    - develop
    - gh-pages
# force container based infra
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
sudo: false
cache:
  directories:
    - node_modules
env:
  global:
    - secure: Z8Ujy1KGYhmc+G5MAlPL377PVseJlhMjgr6jzTh6+IOnEEzXbYF2cvjvJfX7nJI16Y+/b5w+TV1relIocFZqA+wDsGIUNzyZxZH4/dqlVS5PQ190tRe6U27vMs/rIKSkhIl2hWdIJv38ScwFjAwAdSFePJ/ytgyHt5fNK0/Atd0CLrARK1PC8e6HhVQF5y8uZ10eH0TbByZGI3Ts+0VUkyxKcNpTZ+Y4QHEXSeDZ748j3acOfRDERyJI+LQ3y4zFf92dy1HQftaVbhkUU6yP+h2zg0+74fj+ZuSAYRc6OBab2PnJzgOQSN0wl1+PvUURRnfcru1ISr+RCQ9jZK0F2cDItcgxgAhO7wx6xgzrMLxE8Om4pIZ92bOJw85ZuFdiLrnwc9NKwYWvK7Rnh6WR6FUD2MLSHW7wxeo8EAKZ5SgmE3jJXfPadnJU1nEpMWhNA/Fhyr/xWwP2fiFHiycs+YXr4uDqjy90yxp/2Vb1BIr+WAEeYxhwXtS7EZm2n8tKFAl9xUc6eTU/ptYzwJ07RpxmByrBmNAqBDEWKdn1YKIZ4KolWri5PjFHF+Om9jdBLz6JWFkIS0gPQ95Bzr62oDErLgwdQgCi0PhREtEfj9fViOgiw9cyEG9Zh3z39jDWGy6GoLNB5FIbl7q+PZSi/I0rjA6kl7XAhF+lrhlNwzQ=
    - secure: OzAaYh3oG04VhBvuaCwq6GuIzRt6AuiyP1U8Q/arlC/3osFTRkyt64CMRlEZIso74C4eLGDeKGUhimBViurIzvDc2meu88ik41XFPZIJFXfeqrAhCELgJcnTCkRR4ztC3GA6DLVM02qhT/5ENRZ8pcqmHIKvvIoHWQ1l8s8dSBBUSD/0MxAyk9Opzg2qFxmZ8u5/HHSBwdYC0iy6sOBKbMoUocz2UHowfPk0efzZWAgKx3BQyKa+ImYUA0/o6Okmq04naqafjeVciWkXrF0YURPUVus0peNkqjxLdGMZeudxszPNp0fJ7rhSOKBlYwOtg9K98PMWWT1Ar7+TmssIYCrRTlVHeKmzNLOok/YBBvvcd+4kIo0IkO5dPFkpYQ//hKOF6mdvRa1KMlFwSgIVjMjrCikiHBnppheWXffWxWHGWPyfla0uTbwR6o4ONcRCJgTbPoi/xZOFS4ISBiECqCWjNhidOATSyPatBe2tABU2LN5WKqnPDzmnHl/ZusglpPiN1vrEsCyNsoyD6nFz0cVZasR4NKrgqQUzy8cxQhtNuupEW7nMCw8s79bcfE/CsP0A0sGOhDXti+ieAV1tra22US3LMUqysH2DwZakA3dbQtcFoO69Rp/7pWRnDwB2+mEPUJJrXq8tAspvjssalQYVHF6aDGgj5SFXAZYfArs=
    - secure: A1jTbS5zp1j+tG3ncfQKha4oInbpTLKbB1Aokv1pCNf/Ai+4D7220feXszfpSlIamPTOUj0ZXN5b4OTOl77+Xc+Wqr/MESfHbNNlat7rZdesUhRWo5uZFsZW8QDPIkCAHw35GJ1pDl8AbfT4GDjLh+VvjPSD5eysr6aH861ov5Qj0V7KDk0jYzNLICjsiDS8Qm1y1HOWDyUUGBoVTFuMkicDdpVbiHVROMOHR2fj9i/4ROoLNdEuBZ3YCn8QxySxu/BUXgL6PwI6DUPeqfqh35sV4rpsvm7rtsMd//W/OOeRn/7LR8keRugLdfKhRRQmA5KitQhsh7SoZ1KgKmsp3BgdLG0I81ytJyXBrXvofnJkU8oetq/C1cvYSF2FjEv0BcFl4N/YT/sKpJCxJ6VhV9OY0OvbOd3dMFitETqc1eOzqpGkELkVtEs7RzsYkIyDjg691ikJFicbNBb7aqD/6TIj07gTr+649eLSMjrBvtNZIyExz7vqvXog7Day8/ab/i8K7Wp36vHce2uL6I3ipijAadxaHpLbDA0JUCempLNQabTgO88U+J+6MFe9SuPuVJ0EHW/rMZWQpCjTjZETIbFS0wclhBsPbAOp6M8y1UewF74VtnTGKl1qIau0qeZAdSo16G4q2SrMf/nXhuLkCZUtItjW/mqNGvNA0FrxMWY=
