version: 2
jobs:
  build:
    working_directory: ~/react-instantsearch

    docker:
      - image: circleci/node:8.11.4-browsers

    environment:
      FIREFOX_VERSION: '56.0'

    steps:
      - checkout

      - run:
          name: Install specific FF version
          command: |
            wget -O "/tmp/firefox-$FIREFOX_VERSION.tar.bz2" "https://download-installer.cdn.mozilla.net/pub/firefox/releases/$FIREFOX_VERSION/linux-x86_64/en-US/firefox-$FIREFOX_VERSION.tar.bz2"
            tar -jxf "/tmp/firefox-$FIREFOX_VERSION.tar.bz2" -C "/tmp/"
            sudo mv "/tmp/firefox" "/opt/firefox-$FIREFOX_VERSION"
            sudo ln -sf "/opt/firefox-$FIREFOX_VERSION/firefox" "/usr/bin/firefox"
            hash -r
            firefox --version

      - run:
          name: Install specific Yarn version
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
            echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV

      - restore_cache:
          name: Restore Yarn cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: |
            yarn install

      - save_cache:
          name: Save Yarn cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn lint
      - run: yarn test:ci
      - run: yarn test:e2e
      - run: yarn test:build
      - run: yarn test:examples
